version: 2.1

orbs:
  cli: circleci/circleci-cli@dev:alpha
  orb-tools: circleci/orb-tools@9.0

# Pipeline parameters
parameters:
  # These pipeline parameters are required by the "trigger-integration-tests-workflow"
  # job, by default.
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"

jobs:
  test:
    parameters:
      executor:
        type: executor

    executor: <<parameters.executor>>

    steps:
      - cli/install
      - cli/setup

orb_prep_jobs: &orb_prep_jobs
  [
    orb-tools/lint,
    orb-tools/pack
  ]

prod-deploy_requires: &prod-deploy_requires
  [
    alpine,
    machine,
    mac,
    docker,
    ci-docker,
    cimg,
    oracle
  ]

workflows:
  lint_pack-validate_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint

      - orb-tools/pack

      - orb-tools/publish-dev:
          orb-name: circleci/circleci-cli
          context: orb-publishing
          requires: *orb_prep_jobs

      - orb-tools/trigger-integration-tests-workflow:
          context: orb-publishing
          requires: [orb-tools/publish-dev]

  integration-tests_prod-release:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      # alpine
      - test:
          name: alpine
          context: orb-publishing
          executor: orb-tools/alpine

      # machine
      - test:
          name: machine
          context: orb-publishing
          executor: orb-tools/machine

      # mac
      - test:
          name: mac
          context: orb-publishing
          executor: orb-tools/macos

      # docker
      - test:
          name: docker
          context: orb-publishing
          executor: orb-tools/node

      # ci-docker
      - test:
          name: ci-docker
          context: orb-publishing
          executor:
            name: orb-tools/node-cci
            tag: boron-browsers

      # new ci-docker
      - test:
          name: cimg
          context: orb-publishing
          executor: orb-tools/ubuntu

      # oracle
      - test:
          name: oracle
          context: orb-publishing
          executor: orb-tools/oracle

      - orb-tools/dev-promote-prod-from-commit-subject:
          context: orb-publishing
          orb-name: circleci/circleci-cli
          add-pr-comment: true
          bot-token-variable: GHI_TOKEN
          bot-user: cpe-bot
          fail-if-semver-not-indicated: true
          publish-version-tag: true
          ssh-fingerprints: 72:af:5d:cd:d3:4c:52:5d:6c:c6:5c:69:87:42:df:37
          requires: *prod-deploy_requires
          filters:
            branches:
              only: master
