description: >
  The circleci-cli Docker image, which includes the CircleCI CLI

parameters:
  tag:
    type: string
    default: latest
    description: >
      What version of the CircleCI CLI Docker image? For full list, see
      https://hub.docker.com/r/circleci/circleci-cli/tags
  resource_class:
    type: enum
    default: "small"
    description: resource_class to use for the executor
    enum: ["small", "medium", "medium+", "large", "xlarge", "2xlarge", "2xlarge+"]

docker:
  - image: circleci/circleci-cli:<<parameters.tag>>
resource_class: << parameters.resource_class >>
