description: >
  The circleci-cli Docker image, which includes the CircleCI CLI

parameters:
  tag:
    type: string
    default: latest
    description: >
      What version of the CircleCI CLI Docker image? For full list, see
      https://hub.docker.com/r/circleci/circleci-cli/tags

docker:
  - image: circleci/circleci-cli:<<parameters.tag>>
